- hosts: all
  vars:
    user_email: user@example.edu

  tasks:

    - name: import Microsoft GPG key
      apt_key: 
        url: https://packages.microsoft.com/keys/microsoft.asc
      become: yes
    
    - name: add vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      become: yes

    - name: configure vim
      copy:
        src: files/.vimrc
        dest: "{{ ansible_env.HOME }}/.vimrc"

    - name: Add git-core ppa
      apt_repository:
        repo: ppa:git-core/ppa
      become: yes

    - name: install git
      package:
        name: git
        state: latest
      become: yes

    - name: Update .gitconfig
      git_config:
        name: user.email
        scope: global
        value: '{{ user_email }}'

    - name: install vscode
      package:
        name: code
        state: present
      become: yes

    - name: install virtualbox
      package:
        name: virtualbox
        state: present
      become: yes

    - name: install vagrant
      package:
        name: vagrant
        state: present
      become: yes

    - name: install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: install node
      shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node'
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/bash


    - name: install bakerx
      shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && mkdir -p src && cd src && git clone https://github.com/ottomatica/bakerx && cd bakerx && npm install && npm link'
      args:
        creates: '{{ ansible_env.HOME}}/src/bakerx'
        executable: /bin/bash

    - name: Install opunit
      shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install opunit -g'
      args:
        creates: '{{ ansible_env.HOME}}/.nvm/versions/node/v13.6.0/bin/opunit'
        executable: /bin/bash

    - name: Install java
      package:
        name: openjdk-11-jdk
        state: present
      become: yes 

